/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://maven.pkg.github.com/InstaCode/*")
    }
}

dependencies {
    implementation("io.rest-assured:rest-assured:4.4.0")
    implementation("org.springframework.cloud:spring-cloud-starter-config:3.0.4")
    implementation("org.springframework.cloud:spring-cloud-starter-eureka:1.3.0.RELEASE")
    implementation("org.springframework.cloud:spring-cloud-starter-zuul:1.4.7.RELEASE")
    implementation("org.springframework.boot:spring-boot-starter-security:2.5.2")
    implementation("org.springframework.session:spring-session:1.3.5.RELEASE")
    implementation("org.springframework.boot:spring-boot-starter-data-redis:2.5.2")
    implementation("org.springframework.cloud:spring-cloud-starter-zipkin:2.2.8.RELEASE")
    implementation("org.springframework.cloud:spring-cloud-starter-feign:1.4.7.RELEASE")
    implementation("org.springframework.boot:spring-boot-starter-web:2.5.2")
    implementation("org.springframework.cloud:spring-cloud-netflix-core:1.4.6.RELEASE")
    implementation("org.springframework.cloud:spring-cloud-sleuth-core:1.2.0.RELEASE")
    implementation("org.springframework.cloud:spring-cloud-sleuth-zipkin:1.2.0.RELEASE")
    implementation("org.springframework.boot:spring-boot:1.5.22.RELEASE")
    implementation("io.rest-assured:rest-assured:4.4.0")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.5.2")
    testImplementation("junit:junit:4.13.2")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.5.2")
}

group = "io.instacode.automation"
version = "1.0-SNAPSHOT"
description = "Automation University Gateway Server"
java.sourceCompatibility = JavaVersion.VERSION_11

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
